const book1 = [
  {
  word: "agree",
  image: "files/01_0001.jpg",
  audio: "assets/hardcodeDbFiles/01_0001.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0001_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0001_example.mp3",
  textMeaning: "To agree is to have the same opinion or belief as another person",
  textExample: "The students agree they have too much homework",
  transcription: "[əgríː]",
  wordTranslate: "согласна",
  textMeaningTranslate: "Согласиться - значит иметь то же мнение или убеждение, что и другой человек",
  textExampleTranslate: "Студенты согласны, что у них слишком много домашней работы",
  id: 1
},
{
  word: "alcohol",
  image: "files/01_0002.jpg",
  audio: "assets/hardcodeDbFiles/01_0002.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0002_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0002_example.mp3",
  textMeaning: "Alcohol is a type of drink that can make people drunk",
  textExample: "A person should not drive a car after he or she has been drinking alcohol",
  transcription: "[ǽlkəhɔ̀ːl]",
  wordTranslate: "алкоголь",
  textMeaningTranslate: "Алкоголь - это тип напитка, который может сделать людей пьяными",
  textExampleTranslate: "Человек не должен водить машину после того, как он выпил алкоголь",
  id: 2
},
{
  word: "arrive",
  image: "files/01_0003.jpg",
  audio: "assets/hardcodeDbFiles/01_0003.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0003_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0003_example.mp3",
  textMeaning: "To arrive is to get somewhere",
  textExample: "They arrived at school at 7 a.m",
  transcription: "[əráiv]",
  wordTranslate: "прибыть",
  textMeaningTranslate: "Приехать значит попасть куда-то",
  textExampleTranslate: "Они прибыли в школу в 7 часов утра",
  id: 3
},
{
  word: "August",
  image: "files/01_0004.jpg",
  audio: "assets/hardcodeDbFiles/01_0004.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0004_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0004_example.mp3",
  textMeaning: "August is the eighth month of the year",
  textExample: "Is your birthday in August?",
  transcription: "[ɔ́ːgəst]",
  wordTranslate: "август",
  textMeaningTranslate: "Август - восьмой месяц года",
  textExampleTranslate: "У тебя день рождения в августе?",
  id: 4
},
{
  word: "boat",
  image: "files/01_0005.jpg",
  audio: "assets/hardcodeDbFiles/01_0005.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0005_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0005_example.mp3",
  textMeaning: "A boat is a vehicle that moves across water",
  textExample: "There is a small boat on the lake",
  transcription: "[bout]",
  wordTranslate: "лодка",
  textMeaningTranslate: "Лодка - это транспортное средство, которое движется по воде",
  textExampleTranslate: "На озере есть маленькая лодка",
  id: 5
},
{
  word: "breakfast",
  image: "files/01_0006.jpg",
  audio: "assets/hardcodeDbFiles/01_0006.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0006_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0006_example.mp3",
  textMeaning: "Breakfast is the morning meal",
  textExample: "I ate eggs for breakfast",
  transcription: "[brekfəst]",
  wordTranslate: "завтрак",
  textMeaningTranslate: "Завтрак - это утренняя трапеза",
  textExampleTranslate: "Я ел яйца на завтрак",
  id: 6
},
{
  word: "camera",
  image: "files/01_0007.jpg",
  audio: "assets/hardcodeDbFiles/01_0007.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0007_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0007_example.mp3",
  textMeaning: "A camera is a piece of equipment that takes pictures",
  textExample: "I brought my camera on my vacation",
  transcription: "[kǽmərə]",
  wordTranslate: "камера",
  textMeaningTranslate: "Камера - это часть оборудования, которая делает снимки",
  textExampleTranslate: "Я принес свою камеру в отпуск",
  id: 7
},
{
  word: "capital",
  image: "files/01_0008.jpg",
  audio: "assets/hardcodeDbFiles/01_0008.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0008_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0008_example.mp3",
  textMeaning: "A capital is a city where a country’s government is based",
  textExample: "The capital of the United States is Washington, D.C",
  transcription: "[kæpətl]",
  wordTranslate: "столица",
  textMeaningTranslate: "Столица - это город, в котором базируется правительство страны",
  textExampleTranslate: "Столица Соединенных Штатов - Вашингтон, округ Колумбия",
  id: 8
},
{
  word: "catch",
  image: "files/01_0009.jpg",
  audio: "assets/hardcodeDbFiles/01_0009.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0009_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0009_example.mp3",
  textMeaning: "To catch is to grab or get something",
  textExample: "Did you catch the ball during the baseball game?",
  transcription: "[kætʃ]",
  wordTranslate: "поймать",
  textMeaningTranslate: "Поймать - значит схватить или получить что-то",
  textExampleTranslate: "Вы поймали мяч во время игры в бейсбол?",
  id: 9
},
{
  word: "duck",
  image: "files/01_0010.jpg",
  audio: "assets/hardcodeDbFiles/01_0010.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0010_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0010_example.mp3",
  textMeaning: "A duck is a small water bird",
  textExample: "People feed ducks at the lake",
  transcription: "[dʌk]",
  wordTranslate: "утка",
  textMeaningTranslate: "Утка - маленькая водяная птица",
  textExampleTranslate: "Люди кормят уток у озера",
  id: 10
},
{
  word: "enjoy",
  image: "files/01_0011.jpg",
  audio: "assets/hardcodeDbFiles/01_0011.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0011_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0011_example.mp3",
  textMeaning: "To enjoy is to like something",
  textExample: "The woman enjoys riding her bicycle",
  transcription: "[indʒɔ́i]",
  wordTranslate: "наслаждаться",
  textMeaningTranslate: "Наслаждаться значит любить что-то",
  textExampleTranslate: "Женщина любит кататься на велосипеде",
  id: 11
},
{
  word: "invite",
  image: "files/01_0012.jpg",
  audio: "assets/hardcodeDbFiles/01_0012.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0012_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0012_example.mp3",
  textMeaning: "To invite is to ask someone to come to a place or event",
  textExample: "I will invite my friends to my birthday party",
  transcription: "[inváit]",
  wordTranslate: "пригласить",
  textMeaningTranslate: "Пригласить - это попросить кого-нибудь прийти на место или событие",
  textExampleTranslate: "Я приглашаю своих друзей на мой день рождения",
  id: 12
},
{
  word: "love",
  image: "files/01_0013.jpg",
  audio: "assets/hardcodeDbFiles/01_0013.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0013_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0013_example.mp3",
  textMeaning: "To love is to like something or someone a lot",
  textExample: "I love my family very much",
  transcription: "[lʌv]",
  wordTranslate: "любовь",
  textMeaningTranslate: "Любить значит любить что-то или кого-то много",
  textExampleTranslate: "Я очень люблю свою семью",
  id: 13
},
{
  word: "month",
  image: "files/01_0014.jpg",
  audio: "assets/hardcodeDbFiles/01_0014.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0014_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0014_example.mp3",
  textMeaning: "A month is one of 12 periods of time in one year",
  textExample: "January is the first month of the year",
  transcription: "[mʌnθ]",
  wordTranslate: "месяц",
  textMeaningTranslate: "Месяц - это один из 12 периодов времени в году",
  textExampleTranslate: "январь - первый месяц года",
  id: 14
},
{
  word: "travel",
  image: "files/01_0015.jpg",
  audio: "assets/hardcodeDbFiles/01_0015.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0015_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0015_example.mp3",
  textMeaning: "To travel is to go to a faraway place on vacation or business",
  textExample: "They will travel to Argentina this summer",
  transcription: "[trǽvəl]",
  wordTranslate: "путешествовать",
  textMeaningTranslate: "Путешествовать - это отправиться в далекое место на отдых или по делам",
  textExampleTranslate: "Этим летом они отправятся в Аргентину",
  id: 15
},
{
  word: "typical",
  image: "files/01_0016.jpg",
  audio: "assets/hardcodeDbFiles/01_0016.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0016_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0016_example.mp3",
  textMeaning: "If something is typical, it is normal, or something that usually happens",
  textExample: "My typical breakfast is toast and eggs",
  transcription: "[típikəl]",
  wordTranslate: "типичный",
  textMeaningTranslate: "Если что-то типичное, это нормально, или что-то, что обычно происходит",
  textExampleTranslate: "Мой типичный завтрак - тост и яйца",
  id: 16
},
{
  word: "visit",
  image: "files/01_0017.jpg",
  audio: "assets/hardcodeDbFiles/01_0017.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0017_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0017_example.mp3",
  textMeaning: "To visit is to go and spend time in another place or see another person",
  textExample: "She wants to visit her grandmother",
  transcription: "[vízit]",
  wordTranslate: "посещение",
  textMeaningTranslate: "Посетить - значит пойти и провести время в другом месте или увидеть другого человека",
  textExampleTranslate: "Она хочет навестить свою бабушку",
  id: 17
},
{
  word: "weather",
  image: "files/01_0018.jpg",
  audio: "assets/hardcodeDbFiles/01_0018.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0018_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0018_example.mp3",
  textMeaning: "Weather is the temperature and the state of the outdoors",
  textExample: "Today’s weather is rainy and cloudy",
  transcription: "[weðər]",
  wordTranslate: "погода",
  textMeaningTranslate: "Погода это температура и состояние на улице",
  textExampleTranslate: "Сегодня погода дождливая и облачная",
  id: 18
},
{
  word: "week",
  image: "files/01_0019.jpg",
  audio: "assets/hardcodeDbFiles/01_0019.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0019_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0019_example.mp3",
  textMeaning: "A week is a period of time that is seven days long",
  textExample: "What are you doing next week?",
  transcription: "[wiːk]",
  wordTranslate: "неделя",
  textMeaningTranslate: "Неделя - это период времени, который длится семь дней",
  textExampleTranslate: "Что ты делаешь на следующей неделе?",
  id: 19
},
{
  word: "wine",
  image: "files/01_0020.jpg",
  audio: "assets/hardcodeDbFiles/01_0020.mp3",
  audioMeaning: "assets/hardcodeDbFiles/01_0020_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/01_0020_example.mp3",
  textMeaning: "Wine is an alcoholic drink made from grapes",
  textExample: "The store carried both red and white wine",
  transcription: "[wain]",
  wordTranslate: "вино",
  textMeaningTranslate: "Вино - это алкогольный напиток из винограда",
  textExampleTranslate: "В магазине было красное и белое вино",
  id: 20
},
{
  word: "adventure",
  image: "files/02_0021.jpg",
  audio: "assets/hardcodeDbFiles/02_0021.mp3",
  audioMeaning: "assets/hardcodeDbFiles/02_0021_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/02_0021_example.mp3",
  textMeaning: "An adventure is a fun or exciting thing that you do",
  textExample: "Riding in the rough water was an adventure",
  transcription: "[ədvéntʃər]",
  wordTranslate: "приключение",
  textMeaningTranslate: "Приключение - это забавная или захватывающая вещь, которую ты делаешь",
  textExampleTranslate: "Езда в бурной воде была приключением",
  id: 21
},
{
  word: "approach",
  image: "files/02_0022.jpg",
  audio: "assets/hardcodeDbFiles/02_0022.mp3",
  audioMeaning: "assets/hardcodeDbFiles/02_0022_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/02_0022_example.mp3",
  textMeaning: "To approach something means to move close to it",
  textExample: "The boy approached his school",
  transcription: "[əpróutʃ]",
  wordTranslate: "подходить",
  textMeaningTranslate: "Подойти к чему-то - значит приблизиться к нему",
  textExampleTranslate: "Мальчик приблизился к своей школе",
  id: 22
},
{
  word: "carefully",
  image: "files/02_0023.jpg",
  audio: "assets/hardcodeDbFiles/02_0023.mp3",
  audioMeaning: "assets/hardcodeDbFiles/02_0023_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/02_0023_example.mp3",
  textMeaning: "Carefully means with great attention, especially to detail or safety",
  textExample: "The baby carefully climbed down the stairs",
  transcription: "[kɛ́ərfəli]",
  wordTranslate: "внимательно",
  textMeaningTranslate: "Осторожно означает с большим вниманием, особенно к деталям или безопасности",
  textExampleTranslate: "Малыш осторожно спускался по лестнице",
  id: 23
},
{
  word: "chemical",
  image: "files/02_0024.jpg",
  audio: "assets/hardcodeDbFiles/02_0024.mp3",
  audioMeaning: "assets/hardcodeDbFiles/02_0024_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/02_0024_example.mp3",
  textMeaning: "A chemical is something that scientists use in chemistry",
  textExample: "The scientist mixed the chemicals",
  transcription: "[kémikəl]",
  wordTranslate: "химический",
  textMeaningTranslate: "Химическое вещество - это то, что ученые используют в химии",
  textExampleTranslate: "Ученый смешал химикаты",
  id: 24
},
{
  word: "create",
  image: "files/02_0025.jpg",
  audio: "assets/hardcodeDbFiles/02_0025.mp3",
  audioMeaning: "assets/hardcodeDbFiles/02_0025_meaning.mp3",
  audioExample: "assets/hardcodeDbFiles/02_0025_example.mp3",
  textMeaning: "To create means to make something new",
  textExample: "She created an igloo from blocks of snow",
  transcription: "[kriéit]",
  wordTranslate: "создайте",
  textMeaningTranslate: "Создать значит создать что-то новое",
  textExampleTranslate: "Она создала иглу из снежных глыб",
  id: 25
},
];


export default book1;